export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const GET_WEATHER_DATA_FAILED = 'GET_WEATHER_DATA_FAILED';
export const GET_CITY_NAME = 'GET_CITY_NAME';
export const GET_CITY_NAME_FAILED = 'GET_CITY_NAME_FAILED';